/**
 * Scientific Datasets Registry for rusty-SUNDIALS Mission Control
 *
 * Contains metadata, access info, and integration status for
 * ITER/fusion datasets used in MHD experimentation.
 */

export const DATASET_CATEGORIES = [
  { id: 'fusion', label: 'Fusion / ITER', color: '#a78bfa', icon: 'atom' },
  { id: 'mhd', label: 'MHD Benchmarks', color: '#00e5ff', icon: 'magnet' },
  { id: 'visualization', label: 'Visualization', color: '#00ff88', icon: 'eye' },
  { id: 'disruption', label: 'Disruption', color: '#ff3d5a', icon: 'alert' },
  { id: 'computational', label: 'Computational', color: '#ffb800', icon: 'cpu' },
];

export const MOCK_DATASETS = [
  {
    id: 'tokamark',
    name: 'TokaMark',
    subtitle: 'MAST Tokamak AI Benchmark',
    category: 'fusion',
    tier: 1,
    status: 'available',
    source: 'UKAEA + IBM + STFC',
    license: 'Open (Hugging Face)',
    format: 'HDF5 / CSV',
    size: '~50 GB (full), task subsets available',
    version: '1.0',
    lastUpdated: '2025-11-15',
    url: 'https://huggingface.co/datasets/UKAEA-IBM-STFC/tokamark-dataset',
    downloadCmd: 'huggingface-cli download UKAEA-IBM-STFC/tokamark-dataset --repo-type dataset --local-dir ./data/tokamark',
    description: 'Real experimental data from the Mega Ampere Spherical Tokamak (MAST) at UKAEA, covering MHD activity, tearing modes, and disruption prediction across 14 benchmark tasks.',
    tasks: [
      'MHD mode detection',
      'Disruption prediction',
      'Profile reconstruction',
      'Equilibrium inference',
    ],
    integration: {
      target: 'tearing_mode_hero_test.rs, fusion_mhd_benchmark.rs',
      dataFlow: 'HDF5 → Python preprocessing → CSV → CVODE initial conditions',
      status: 'planned',
      usedBy: ['tearing_mode_hero_test.rs', 'fusion_mhd_benchmark.rs'],
    },
    parameters: [
      { name: 'Shots', value: '15,000+', unit: 'discharges' },
      { name: 'Tasks', value: '14', unit: 'benchmarks' },
      { name: 'Diagnostics', value: '30+', unit: 'channels' },
    ],
    citations: 1,
    stars: 42,
    shared: true,
  },
  {
    id: 'imas-python',
    name: 'ITER IMAS',
    subtitle: 'Integrated Modeling & Analysis Suite',
    category: 'fusion',
    tier: 1,
    status: 'integrated',
    source: 'ITER Organization',
    license: 'LGPL-3.0',
    format: 'HDF5 / netCDF via IDS',
    size: 'Variable (per scenario)',
    version: 'v2.2.0',
    lastUpdated: '2026-05-01',
    url: 'https://github.com/iterorganization/IMAS-Python',
    downloadCmd: 'pip install imas-python',
    description: 'The official ITER data model — now open-source. Provides standardized plasma scenario data structures (Interface Data Structures / IDS) used across all ITER-member institutions.',
    tasks: [
      'Equilibrium definition (ψ profiles)',
      'Core profile access (T_e, n_e, j)',
      'MHD linear stability data',
      'Magnetic diagnostics',
    ],
    integration: {
      target: 'scripts/fusion_data_integration.py',
      dataFlow: 'imas-python → IDS exploration → CSV/Rust constants → CVODE',
      status: 'active',
      usedBy: ['fusion_data_integration.py', 'export_imas_paraview.py'],
    },
    parameters: [
      { name: 'IDS Types', value: '5', unit: 'structures' },
      { name: 'DD Version', value: '3.42.0', unit: '' },
      { name: 'Status', value: 'Open Source', unit: '' },
    ],
    citations: 28,
    stars: 156,
    shared: true,
  },
  {
    id: 'freegs',
    name: 'FreeGS',
    subtitle: 'Grad-Shafranov Equilibrium Solver',
    category: 'fusion',
    tier: 1,
    status: 'integrated',
    source: 'UKAEA / Fusion Computing Lab',
    license: 'LGPL',
    format: 'Python objects → CSV export',
    size: 'N/A (solver)',
    version: '0.8.1',
    lastUpdated: '2026-03-20',
    url: 'https://github.com/freegs-plasma/freegs',
    downloadCmd: 'pip install freegs',
    description: 'Open-source Grad-Shafranov equilibrium solver. Generates ITER-geometry equilibria (R₀=6.2m, a=2.0m, B₀=5.3T, Ip=15MA) as initial conditions for rusty-SUNDIALS MHD simulations.',
    tasks: [
      'ITER-like equilibrium generation',
      'Poloidal flux ψ(R,Z) computation',
      'Current density j(R) profiles',
      'Shaped plasma boundaries',
    ],
    integration: {
      target: 'scripts/fusion_data_integration.py',
      dataFlow: 'FreeGS solver → ψ(R) midplane profile → iter_equilibrium.csv → Rust',
      status: 'active',
      usedBy: ['fusion_data_integration.py'],
    },
    parameters: [
      { name: 'R₀', value: '6.2', unit: 'm' },
      { name: 'B₀', value: '5.3', unit: 'T' },
      { name: 'Ip', value: '15', unit: 'MA' },
      { name: 'κ', value: '1.7', unit: '' },
    ],
    citations: 12,
    stars: 89,
    shared: true,
  },
  {
    id: 'imas-paraview',
    name: 'IMAS-ParaView',
    subtitle: '3D Disruption Visualization',
    category: 'visualization',
    tier: 1,
    status: 'integrated',
    source: 'ITER Organization',
    license: 'LGPL-3.0',
    format: 'GGD → VTK → ParaView',
    size: 'N/A (tool)',
    version: 'v2.3.0',
    lastUpdated: '2026-03-11',
    url: 'https://github.com/iterorganization/IMAS-ParaView',
    downloadCmd: 'pip install imas-paraview',
    description: 'Official ITER visualization toolkit for 3D post-processing of JOREK disruption simulations. Renders induced currents in vacuum vessel and plasma electron temperature during ITER disruptions. VR-ready output for CAVE-type and HMD systems.',
    tasks: [
      'GGD → VTK format conversion',
      '3D disruption animation',
      'Induced current visualization',
      'T_e field rendering',
      'VR output (HMD/CAVE)',
    ],
    integration: {
      target: 'scripts/export_imas_paraview.py',
      dataFlow: 'CVODE CSV → IMAS HDF5 → VTK → ParaView 3D rendering',
      status: 'active',
      usedBy: ['export_imas_paraview.py'],
    },
    parameters: [
      { name: 'Grid', value: '100×65', unit: 'points' },
      { name: 'Fields', value: '3', unit: '(ψ, T_e, j_φ)' },
      { name: 'Gallery', value: 'Online', unit: '' },
    ],
    citations: 8,
    stars: 28,
    shared: true,
  },
  {
    id: 'fair-mast',
    name: 'FAIR-MAST',
    subtitle: 'Raw MAST Diagnostics Archive',
    category: 'fusion',
    tier: 1,
    status: 'available',
    source: 'UKAEA (Culham Centre)',
    license: 'Open (Public API)',
    format: 'Searchable metadata + raw signals',
    size: '30+ years of data',
    version: 'Live API',
    lastUpdated: '2026-05-10',
    url: 'https://fair-mast.fusion.ukaea.uk/',
    downloadCmd: 'curl https://fair-mast.fusion.ukaea.uk/api/v1/shots',
    description: 'Over 30 years of MAST experimental data with searchable metadata. Provides ground-truth validation for reduced MHD simulations with specific discharge shots showing known tearing mode activity.',
    tasks: [
      'Shot-level diagnostic access',
      'MHD mode activity ground truth',
      'Time-series magnetic signals',
    ],
    integration: {
      target: 'exp5_fogno_xmhd.rs',
      dataFlow: 'FAIR-MAST API → JSON → Python → CSV → Rust',
      status: 'planned',
      usedBy: ['exp5_fogno_xmhd.rs'],
    },
    parameters: [
      { name: 'History', value: '30+', unit: 'years' },
      { name: 'Diagnostics', value: '100+', unit: 'types' },
      { name: 'Access', value: 'Public', unit: 'API' },
    ],
    citations: 45,
    stars: 0,
    shared: true,
  },
  {
    id: 'plasmapy',
    name: 'PlasmaPy',
    subtitle: 'Community Python Plasma Package',
    category: 'computational',
    tier: 2,
    status: 'integrated',
    source: 'PlasmaPy Community',
    license: 'BSD-3',
    format: 'Python computations → CSV',
    size: 'N/A (library)',
    version: '2026.2.0',
    lastUpdated: '2026-02-15',
    url: 'https://github.com/PlasmaPy/PlasmaPy',
    downloadCmd: 'pip install plasmapy',
    description: 'Community-driven Python package for plasma physics. Computes Alfvén speed, resistivity, Lundquist number, and other MHD parameters from experimental data → feeds into rusty-SUNDIALS RHS coefficients.',
    tasks: [
      'Alfvén speed computation',
      'Lundquist number S calculation',
      'Resistivity profiles',
      'Tearing mode growth rates',
    ],
    integration: {
      target: 'scripts/fusion_data_integration.py',
      dataFlow: 'PlasmaPy → ITER plasma constants → iter_plasma_constants.rs',
      status: 'active',
      usedBy: ['fusion_data_integration.py'],
    },
    parameters: [
      { name: 'v_A', value: '8.18×10⁶', unit: 'm/s' },
      { name: 'S', value: '2.06×10⁹', unit: '' },
      { name: 'τ_R', value: '502.7', unit: 's' },
      { name: 'γ', value: '10.6', unit: 's⁻¹' },
    ],
    citations: 220,
    stars: 510,
    shared: true,
  },
  {
    id: 'disruption-py',
    name: 'disruption-py',
    subtitle: 'MIT PSFC Disruption Framework',
    category: 'disruption',
    tier: 2,
    status: 'available',
    source: 'MIT Plasma Science & Fusion Center',
    license: 'Open Source',
    format: 'Python + tokamak shot data',
    size: 'Variable',
    version: '1.x',
    lastUpdated: '2025-09-01',
    url: 'https://github.com/MIT-PSFC/disruption-py',
    downloadCmd: 'pip install disruption-py',
    description: 'Physics-based disruption analysis framework covering C-Mod, DIII-D, and EAST tokamaks. Extracts tearing mode stability parameters (Δ\') from real data as ODE boundary conditions.',
    tasks: [
      'Tearing mode Δ\' extraction',
      'Disruption onset prediction',
      'Multi-device analysis (C-Mod, DIII-D, EAST)',
    ],
    integration: {
      target: 'tearing_mode_hero_test.rs',
      dataFlow: 'disruption-py → Δ\' parameters → CSV → Rust boundary conditions',
      status: 'planned',
      usedBy: ['tearing_mode_hero_test.rs'],
    },
    parameters: [
      { name: 'Devices', value: '3', unit: 'tokamaks' },
      { name: 'Focus', value: 'Δ\'', unit: 'stability' },
    ],
    citations: 35,
    stars: 67,
    shared: true,
  },
  {
    id: 'jorek',
    name: 'JOREK',
    subtitle: 'Non-linear Extended MHD Code',
    category: 'mhd',
    tier: 3,
    status: 'reference',
    source: 'CEA / EUROfusion',
    license: 'Research collaboration',
    format: 'Published benchmarks + IMAS-ParaView viz',
    size: 'N/A (reference)',
    version: 'N/A',
    lastUpdated: '2026-04-01',
    url: 'https://jorek.eu/',
    downloadCmd: null,
    description: 'Gold-standard non-linear extended MHD code for tearing modes, ELMs, and disruptions. Published benchmark data serves as validation targets for rusty-SUNDIALS. IMAS-ParaView renders its ITER disruption simulations showing induced currents and T_e evolution.',
    tasks: [
      '2/1 tearing mode growth rates (γ vs S)',
      'CASTOR3D linear code comparison (1-2% agreement)',
      'ITER disruption visualization via IMAS-ParaView',
      'Vacuum vessel induced current rendering',
    ],
    integration: {
      target: 'fusion_mhd_benchmark.rs',
      dataFlow: 'Published literature → validation targets → benchmark comparison',
      status: 'active',
      usedBy: ['fusion_mhd_benchmark.rs', 'tearing_mode_hero_test.rs'],
    },
    parameters: [
      { name: 'R/a', value: '10', unit: 'aspect ratio' },
      { name: 'S range', value: '10⁴–10⁸', unit: 'Lundquist' },
      { name: 'Accuracy', value: '1–2%', unit: 'vs CASTOR3D' },
    ],
    citations: 380,
    stars: 0,
    shared: false,
  },
  {
    id: 'iter-equilibrium',
    name: 'ITER Equilibrium',
    subtitle: 'Generated FreeGS Midplane Profile',
    category: 'fusion',
    tier: 1,
    status: 'generated',
    source: 'rusty-SUNDIALS (auto-generated)',
    license: 'Apache 2.0',
    format: 'CSV (100 radial points)',
    size: '8,558 bytes',
    version: 'v11.5.0',
    lastUpdated: '2026-05-16',
    url: null,
    downloadCmd: 'python3 scripts/fusion_data_integration.py',
    description: 'Auto-generated ITER-like equilibrium profile computed by FreeGS. Contains ψ(R), T_e(R), n_e(R), and j_φ(R) along the midplane for direct CVODE integration.',
    tasks: [
      'CVODE initial condition generation',
      'MHD RHS coefficient computation',
      'ParaView visualization input',
    ],
    integration: {
      target: 'data/fusion/iter_equilibrium.csv',
      dataFlow: 'FreeGS → CSV → Rust (include!()) → CVODE solver',
      status: 'active',
      usedBy: ['tearing_mode_hero_test.rs', 'fusion_mhd_benchmark.rs'],
    },
    parameters: [
      { name: 'ψ range', value: '35.0–36.1', unit: 'Wb' },
      { name: 'T_e(0)', value: '25.0', unit: 'keV' },
      { name: 'n_e(0)', value: '1×10²⁰', unit: 'm⁻³' },
      { name: 'Points', value: '100', unit: 'radial' },
    ],
    citations: 0,
    stars: 0,
    shared: true,
  },
  {
    id: 'vr-fusion',
    name: 'VR Fusion Viz',
    subtitle: 'NIFS / EUROfusion VR System',
    category: 'visualization',
    tier: 3,
    status: 'reference',
    source: 'NIFS + EUROfusion',
    license: 'Research',
    format: 'CAVE-type VR + HMDs',
    size: 'N/A',
    version: 'N/A',
    lastUpdated: '2026-04-15',
    url: 'https://link.springer.com/article/10.1007/s10894-026-00549-z',
    downloadCmd: null,
    description: 'Immersive VR visualization of fusion plasma data using CAVE-type systems and head-mounted displays. Enables multi-researcher collaborative analysis of MHD simulation results. Combined with IMAS-ParaView outputs for tearing mode and disruption analysis.',
    tasks: [
      'Immersive 3D plasma exploration',
      'Multi-researcher collaborative analysis',
      'CAD + simulation data overlay',
    ],
    integration: {
      target: 'data/fusion/vtk_output/',
      dataFlow: 'VTK → ParaView VR plugin → HMD rendering',
      status: 'planned',
      usedBy: [],
    },
    parameters: [
      { name: 'Technology', value: 'CAVE + HMD', unit: '' },
      { name: 'Reference', value: 'J. Fusion Energy', unit: '2026' },
    ],
    citations: 5,
    stars: 0,
    shared: false,
  },
];

export const DATASET_STATS = {
  total: MOCK_DATASETS.length,
  integrated: MOCK_DATASETS.filter(d => d.status === 'integrated' || d.status === 'generated' || d.status === 'active').length,
  available: MOCK_DATASETS.filter(d => d.status === 'available').length,
  reference: MOCK_DATASETS.filter(d => d.status === 'reference').length,
  totalCitations: MOCK_DATASETS.reduce((sum, d) => sum + d.citations, 0),
  totalFiles: 3,
  generatedFiles: [
    { name: 'iter_equilibrium.csv', size: '8,558 bytes', path: 'data/fusion/iter_equilibrium.csv' },
    { name: 'iter_plasma_constants.rs', size: '798 bytes', path: 'data/fusion/iter_plasma_constants.rs' },
    { name: 'iter_plasma_parameters.csv', size: '262 bytes', path: 'data/fusion/iter_plasma_parameters.csv' },
  ],
};
