#!/usr/bin/env pvpython
"""
ParaView automated rendering script for rusty-SUNDIALS ITER equilibrium.

Usage:
  pvpython render_iter_equilibrium.py
  # Or open ParaView → Tools → Python Shell → Run Script

Generated by: scripts/export_imas_paraview.py
"""

from paraview.simple import *

# Load VTK file
vtk_file = "/Volumes/MacCleanerStorage/xdev/x-rusty-SUNDIALS/rusty-SUNDIALS/data/fusion/vtk_output/iter_midplane.vtk"
reader = LegacyVTKReader(FileNames=[vtk_file])
Show(reader)

# Set up electron temperature visualization
display = GetDisplayProperties(reader)
ColorBy(display, ("POINTS", "Te_keV"))
display.RescaleTransferFunctionToDataRange()

# Get color transfer function
te_lut = GetColorTransferFunction("Te_keV")
te_lut.ApplyPreset("Inferno (matplotlib)", True)

# Set camera for tokamak cross-section view
camera = GetActiveCamera()
camera.SetPosition(6.2, 0, 15)
camera.SetFocalPoint(6.2, 0, 0)
camera.SetViewUp(0, 1, 0)
camera.SetParallelScale(5.0)

# Add color bar
color_bar = GetScalarBar(te_lut)
color_bar.Title = "T_e [keV]"
color_bar.ComponentTitle = ""
color_bar.Visibility = 1

# Add title
text = Text()
text.Text = "rusty-SUNDIALS v11.5 — ITER Equilibrium (FreeGS)"
text_display = Show(text)
text_display.FontSize = 18
text_display.Position = [0.05, 0.92]

# Render
RenderAllViews()
print("✅ ParaView render complete")

# Save screenshot
screenshot_path = "/Volumes/MacCleanerStorage/xdev/x-rusty-SUNDIALS/rusty-SUNDIALS/data/fusion/vtk_output/iter_Te_midplane.png"
SaveScreenshot(screenshot_path, magnification=2)
print(f"📸 Screenshot saved: {screenshot_path}")
