// AUTO-GENERATED BY EXACT-MATH MIDDLEWARE (Lean 4 Consilience Bridge)
// Do not edit manually.

pub const FRICKE_Y: f64 = 0.28867513459481287_f64;
pub const ORBIFOLD_Y: f64 = 0.8660254037844386_f64;
pub const ATTRACTOR_TOLERANCE: f64 = 1e-3;
