#!/usr/bin/env python3
"""
IMAS-ParaView Visualization Export for rusty-SUNDIALS

Converts CVODE MHD simulation CSV output → IMAS IDS (HDF5) → VTK for ParaView.

End-to-end pipeline:
  1. Read CSV from rusty-SUNDIALS MHD examples
  2. Create IMAS-compatible HDF5 with equilibrium + core_profiles IDS
  3. Generate VTK files for ParaView 3D visualization
  4. Create ParaView Python script for time-lapse animation

Dependencies: pip install imas-python h5py numpy matplotlib
Optional:     pip install imas-paraview (for GGD→VTK conversion)

Usage:
  python3 scripts/export_imas_paraview.py data/fusion/iter_equilibrium.csv
"""

import os
import sys
import csv
import json
import numpy as np
from datetime import datetime

# ═══════════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════════

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(PROJECT_ROOT, "data", "fusion")
VTK_DIR = os.path.join(DATA_DIR, "vtk_output")
IMAS_DIR = os.path.join(DATA_DIR, "imas_export")


# ═══════════════════════════════════════════════════════════════════
# Part 1: Read rusty-SUNDIALS CSV Output
# ═══════════════════════════════════════════════════════════════════

def read_equilibrium_csv(csv_path: str) -> dict:
    """Read ITER equilibrium CSV generated by fusion_data_integration.py."""
    data = {
        "rho": [], "R_m": [], "psi_Wb": [], "psi_norm": [],
        "Te_keV": [], "ne_m3": [], "j_phi_Am2": [],
    }
    with open(csv_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            for key in data:
                data[key].append(float(row[key]))
    for key in data:
        data[key] = np.array(data[key])
    
    print(f"  📊 Loaded {len(data['rho'])} radial points from {csv_path}")
    return data


# ═══════════════════════════════════════════════════════════════════
# Part 2: Export to IMAS-compatible HDF5
# ═══════════════════════════════════════════════════════════════════

def export_imas_hdf5(data: dict, output_dir: str):
    """
    Export equilibrium data to IMAS-compatible HDF5 format.
    
    This creates a minimal IMAS-like structure that IMAS-ParaView
    can read for 3D visualization.
    """
    try:
        import h5py
    except ImportError:
        print("  ⚠️  h5py not installed. Run: pip install h5py")
        return None

    os.makedirs(output_dir, exist_ok=True)
    hdf5_path = os.path.join(output_dir, "rusty_sundials_equilibrium.h5")

    with h5py.File(hdf5_path, "w") as f:
        # IMAS metadata
        f.attrs["creator"] = "rusty-SUNDIALS v11.5.0"
        f.attrs["creation_date"] = datetime.utcnow().isoformat()
        f.attrs["description"] = "ITER-like equilibrium from FreeGS + rusty-SUNDIALS MHD"
        f.attrs["imas_version"] = "3.42.0"

        # equilibrium IDS
        eq = f.create_group("equilibrium")
        eq.attrs["ids_type"] = "equilibrium"
        
        ts = eq.create_group("time_slice_0")
        ts.attrs["time"] = 0.0
        
        p1d = ts.create_group("profiles_1d")
        p1d.create_dataset("rho_tor_norm", data=data["rho"])
        p1d.create_dataset("psi", data=data["psi_Wb"])
        p1d.create_dataset("psi_norm", data=data["psi_norm"])

        # Global quantities
        gq = ts.create_group("global_quantities")
        gq.attrs["ip"] = 15e6  # Plasma current [A]
        gq.attrs["magnetic_axis_r"] = 6.2  # R0 [m]
        gq.attrs["magnetic_axis_z"] = 0.0  # Z0 [m]

        # core_profiles IDS
        cp = f.create_group("core_profiles")
        cp.attrs["ids_type"] = "core_profiles"
        
        cp_ts = cp.create_group("time_slice_0")
        cp_ts.attrs["time"] = 0.0
        
        p = cp_ts.create_group("profiles_1d")
        p.create_dataset("rho_tor_norm", data=data["rho"])
        p.create_dataset("electrons_temperature", data=data["Te_keV"] * 1e3)  # keV → eV
        p.create_dataset("electrons_density", data=data["ne_m3"])
        p.create_dataset("j_tor", data=data["j_phi_Am2"])

        # R grid for spatial reference
        p.create_dataset("grid_R", data=data["R_m"])

    print(f"  ✅ IMAS HDF5 exported: {hdf5_path}")
    print(f"     Size: {os.path.getsize(hdf5_path):,} bytes")
    return hdf5_path


# ═══════════════════════════════════════════════════════════════════
# Part 3: Generate VTK for ParaView
# ═══════════════════════════════════════════════════════════════════

def generate_vtk_midplane(data: dict, output_dir: str):
    """
    Generate a VTK structured grid file for ParaView visualization.
    
    Creates a 2D midplane cross-section (R, Z) with ψ, T_e, j_phi
    mapped as point data — suitable for direct loading in ParaView.
    """
    os.makedirs(output_dir, exist_ok=True)

    # Create a 2D grid in (R, Z) plane
    R = data["R_m"]
    n_r = len(R)
    n_z = 65  # Z resolution
    
    Z = np.linspace(-3.4, 3.4, n_z)  # ITER: ±κ*a = ±3.4m
    
    # Build 2D fields (axisymmetric → extend radially)
    psi_2d = np.zeros((n_r, n_z))
    te_2d = np.zeros((n_r, n_z))
    j_2d = np.zeros((n_r, n_z))
    
    rho = data["rho"]
    for iz in range(n_z):
        z = Z[iz]
        # Simple axisymmetric model: fields decay as Gaussian in Z
        z_decay = np.exp(-z**2 / (2 * 1.7**2))  # κ*a ~ 3.4
        psi_2d[:, iz] = data["psi_Wb"] * z_decay
        te_2d[:, iz] = data["Te_keV"] * z_decay
        j_2d[:, iz] = data["j_phi_Am2"] * z_decay

    # Write VTK Structured Grid
    vtk_path = os.path.join(output_dir, "iter_midplane.vtk")
    with open(vtk_path, "w") as f:
        f.write("# vtk DataFile Version 3.0\n")
        f.write("rusty-SUNDIALS ITER Equilibrium (FreeGS) — midplane\n")
        f.write("ASCII\n")
        f.write("DATASET STRUCTURED_GRID\n")
        f.write(f"DIMENSIONS {n_r} {n_z} 1\n")
        f.write(f"POINTS {n_r * n_z} float\n")
        
        for iz in range(n_z):
            for ir in range(n_r):
                f.write(f"{R[ir]:.6f} {Z[iz]:.6f} 0.0\n")
        
        f.write(f"\nPOINT_DATA {n_r * n_z}\n")
        
        # ψ (poloidal flux)
        f.write("SCALARS psi_Wb float 1\n")
        f.write("LOOKUP_TABLE default\n")
        for iz in range(n_z):
            for ir in range(n_r):
                f.write(f"{psi_2d[ir, iz]:.10e}\n")
        
        # T_e (electron temperature)
        f.write("SCALARS Te_keV float 1\n")
        f.write("LOOKUP_TABLE default\n")
        for iz in range(n_z):
            for ir in range(n_r):
                f.write(f"{te_2d[ir, iz]:.6f}\n")
        
        # j_phi (toroidal current density)
        f.write("SCALARS j_phi_Am2 float 1\n")
        f.write("LOOKUP_TABLE default\n")
        for iz in range(n_z):
            for ir in range(n_r):
                f.write(f"{j_2d[ir, iz]:.4e}\n")

    print(f"  ✅ VTK exported: {vtk_path}")
    print(f"     Grid: {n_r}×{n_z} = {n_r * n_z} points")
    print(f"     Fields: ψ, T_e, j_φ")
    print(f"     Size: {os.path.getsize(vtk_path):,} bytes")
    return vtk_path


# ═══════════════════════════════════════════════════════════════════
# Part 4: ParaView Python Automation Script
# ═══════════════════════════════════════════════════════════════════

def generate_paraview_script(vtk_path: str, output_dir: str):
    """Generate a ParaView Python script for automated rendering."""
    script_path = os.path.join(output_dir, "render_iter_equilibrium.py")
    
    with open(script_path, "w") as f:
        f.write(f'''#!/usr/bin/env pvpython
"""
ParaView automated rendering script for rusty-SUNDIALS ITER equilibrium.

Usage:
  pvpython {os.path.basename(script_path)}
  # Or open ParaView → Tools → Python Shell → Run Script

Generated by: scripts/export_imas_paraview.py
"""

from paraview.simple import *

# Load VTK file
vtk_file = "{os.path.abspath(vtk_path)}"
reader = LegacyVTKReader(FileNames=[vtk_file])
Show(reader)

# Set up electron temperature visualization
display = GetDisplayProperties(reader)
ColorBy(display, ("POINTS", "Te_keV"))
display.RescaleTransferFunctionToDataRange()

# Get color transfer function
te_lut = GetColorTransferFunction("Te_keV")
te_lut.ApplyPreset("Inferno (matplotlib)", True)

# Set camera for tokamak cross-section view
camera = GetActiveCamera()
camera.SetPosition(6.2, 0, 15)
camera.SetFocalPoint(6.2, 0, 0)
camera.SetViewUp(0, 1, 0)
camera.SetParallelScale(5.0)

# Add color bar
color_bar = GetScalarBar(te_lut)
color_bar.Title = "T_e [keV]"
color_bar.ComponentTitle = ""
color_bar.Visibility = 1

# Add title
text = Text()
text.Text = "rusty-SUNDIALS v11.5 — ITER Equilibrium (FreeGS)"
text_display = Show(text)
text_display.FontSize = 18
text_display.Position = [0.05, 0.92]

# Render
RenderAllViews()
print("✅ ParaView render complete")

# Save screenshot
screenshot_path = "{os.path.join(output_dir, 'iter_Te_midplane.png')}"
SaveScreenshot(screenshot_path, magnification=2)
print(f"📸 Screenshot saved: {{screenshot_path}}")
''')

    print(f"  ✅ ParaView script: {script_path}")
    return script_path


# ═══════════════════════════════════════════════════════════════════
# Part 5: Summary metadata
# ═══════════════════════════════════════════════════════════════════

def write_manifest(output_dir: str, files: dict):
    """Write a manifest JSON for tracking generated visualization files."""
    manifest = {
        "generator": "rusty-SUNDIALS v11.5.0 / export_imas_paraview.py",
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "imas_version": "3.42.0",
        "paraview_version": "5.12+",
        "imas_paraview_version": "2.3.0",
        "files": files,
        "visualization_targets": [
            "IMAS-ParaView (3D GGD → VTK)",
            "ParaView standalone (VTK structured grid)",
            "VR (CAVE-type / HMD via ParaView VR plugin)",
        ],
        "iter_parameters": {
            "R0_m": 6.2,
            "a_m": 2.0,
            "B0_T": 5.3,
            "Ip_MA": 15.0,
            "kappa": 1.7,
            "delta": 0.33,
        },
        "references": {
            "imas_paraview": "https://github.com/iterorganization/IMAS-ParaView",
            "eurofusion_3d_viz": "https://euro-fusion.org/member-news/3d-visualization-brings-nuclear-fusion-to-life/",
            "springer_fusion_viz": "https://link.springer.com/article/10.1007/s10894-026-00549-z",
        },
    }
    manifest_path = os.path.join(output_dir, "manifest.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"  📋 Manifest: {manifest_path}")


# ═══════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════

def main():
    print("╔══════════════════════════════════════════════════════════════════╗")
    print("║  IMAS-ParaView Visualization Export for rusty-SUNDIALS         ║")
    print("║  CVODE MHD Output → IMAS IDS (HDF5) → VTK → ParaView 3D     ║")
    print("╚══════════════════════════════════════════════════════════════════╝")

    # Determine input file
    csv_path = os.path.join(DATA_DIR, "iter_equilibrium.csv")
    if len(sys.argv) > 1:
        csv_path = sys.argv[1]

    if not os.path.exists(csv_path):
        print(f"  ❌ Input file not found: {csv_path}")
        print("  Run first: python3 scripts/fusion_data_integration.py")
        sys.exit(1)

    # Step 1: Read CSV
    print("\n  Step 1: Reading CVODE output...")
    data = read_equilibrium_csv(csv_path)

    # Step 2: Export IMAS HDF5
    print("\n  Step 2: Exporting IMAS-compatible HDF5...")
    hdf5_path = export_imas_hdf5(data, IMAS_DIR)

    # Step 3: Generate VTK
    print("\n  Step 3: Generating VTK for ParaView...")
    vtk_path = generate_vtk_midplane(data, VTK_DIR)

    # Step 4: ParaView automation script
    print("\n  Step 4: Creating ParaView render script...")
    pv_script = generate_paraview_script(vtk_path, VTK_DIR)

    # Step 5: Write manifest
    print("\n  Step 5: Writing manifest...")
    files = {
        "equilibrium_csv": csv_path,
        "imas_hdf5": hdf5_path,
        "vtk_midplane": vtk_path,
        "paraview_script": pv_script,
    }
    write_manifest(VTK_DIR, files)

    # Summary
    print("\n" + "=" * 70)
    print("  ✅ Visualization export complete!")
    print("=" * 70)
    print(f"\n  Open in ParaView:")
    print(f"    paraview {vtk_path}")
    print(f"\n  Or automate:")
    print(f"    pvpython {pv_script}")
    print(f"\n  IMAS-ParaView (with imas-python):")
    print(f"    paraview --data={hdf5_path}")


if __name__ == "__main__":
    main()
