//! ITER Baseline Scenario Plasma Constants
//!
//! Auto-generated by scripts/fusion_data_integration.py
//! Source: PlasmaPy + ITER design parameters
//!
//! These constants can be used as coefficients in the RHS
//! functions of MHD benchmark examples.

#![allow(dead_code)]

/// B0_T
pub const B0_T: f64 = 5.3000000000e+00;

/// ne_m3
pub const NE_M3: f64 = 1.0000000000e+20;

/// Te_keV
pub const TE_KEV: f64 = 2.5000000000e+01;

/// v_A_ms
pub const V_A_MS: f64 = 8.1808363329e+06;

/// eta_Ohm_m
pub const ETA_OHM_M: f64 = 1.0000000000e-08;

/// tau_R_s
pub const TAU_R_S: f64 = 5.0265482457e+02;

/// tau_A_s
pub const TAU_A_S: f64 = 2.4447378222e-07;

/// S_lundquist
pub const S_LUNDQUIST: f64 = 2.0560684259e+09;

/// gamma_tearing_s1
pub const GAMMA_TEARING_S1: f64 = 1.0566840941e+01;

