name = "RustySundialsProofs"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["RustySundialsProofs"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "repl"
git = "https://github.com/leanprover-community/repl.git"

[[lean_lib]]
name = "RustySundialsProofs"
