// 30 Scientific Use Cases for Rusty-SUNDIALS Education Platform
const CASES = [
// AEROSPACE (1-6)
{id:1,domain:"Aerospace",icon:"🚀",name:"Rocket Trajectory",stiff:false,
 eq:"m\\dot{v}=F_{thrust}-mg-\\frac{1}{2}\\rho v^2 C_D A",
 desc:"Tsiolkovsky rocket equation with drag. Models vertical ascent through atmosphere.",
 vars:["altitude","velocity"],y0:[0,0],tEnd:120,
 params:{thrust:50000,mass:2000,Cd:0.5,area:2},
 rhs:(t,y,f,p)=>{const g=9.81,rho=1.225*Math.exp(-y[0]/8500);f[0]=y[1];f[1]=p.thrust/p.mass-g-0.5*rho*y[1]*Math.abs(y[1])*p.Cd*p.area/p.mass;}},
{id:2,domain:"Aerospace",icon:"🚀",name:"Kepler Orbit",stiff:false,
 eq:"\\ddot{\\mathbf{r}}=-\\frac{\\mu}{|\\mathbf{r}|^3}\\mathbf{r}",
 desc:"Two-body orbital mechanics. Tests energy conservation over many orbits.",
 vars:["x","y","vx","vy"],y0:[1,0,0,1],tEnd:20,
 params:{mu:1},
 rhs:(t,y,f,p)=>{const r=Math.sqrt(y[0]*y[0]+y[1]*y[1])||1e-10,r3=r*r*r;f[0]=y[2];f[1]=y[3];f[2]=-p.mu*y[0]/r3;f[3]=-p.mu*y[1]/r3;}},
{id:3,domain:"Aerospace",icon:"🚀",name:"Atmospheric Re-entry",stiff:true,
 eq:"m\\dot{v}=-\\frac{1}{2}\\rho v^2 C_D A + mg\\sin\\gamma",
 desc:"Spacecraft re-entry heating. Stiff due to exponential density profile.",
 vars:["altitude","velocity","gamma"],y0:[120000,7800,-0.05],tEnd:300,
 params:{mass:3000,Cd:1.2,area:10},
 rhs:(t,y,f,p)=>{const g=9.81,rho=1.225*Math.exp(-y[0]/8500),D=0.5*rho*y[1]*y[1]*p.Cd*p.area;f[0]=y[1]*Math.sin(y[2]);f[1]=-D/p.mass+g*Math.sin(y[2]);f[2]=(g/y[1]-y[1]/6371000)*Math.cos(y[2]);}},
{id:4,domain:"Aerospace",icon:"🚀",name:"Satellite Drag Decay",stiff:false,
 eq:"\\dot{a}=-\\frac{\\rho v C_D A}{m}a",
 desc:"LEO satellite orbit decay due to atmospheric drag over months.",
 vars:["altitude"],y0:[400000],tEnd:86400*180,
 params:{mass:500,Cd:2.2,area:4},
 rhs:(t,y,f,p)=>{const rho=1.225*Math.exp(-y[0]/8500),v=Math.sqrt(3.986e14/(6371000+y[0]));f[0]=-0.5*rho*v*p.Cd*p.area/p.mass*v;}},
{id:5,domain:"Aerospace",icon:"🚀",name:"Gravity Turn",stiff:false,
 eq:"\\dot{\\theta}=\\frac{g\\cos\\theta}{v}",
 desc:"Launch vehicle gravity turn trajectory optimization.",
 vars:["x","y","vx","vy","mass"],y0:[0,0,0,1,50000],tEnd:180,
 params:{thrust:800000,mdot:250,Cd:0.3,area:10},
 rhs:(t,y,f,p)=>{const m=Math.max(y[4],5000),v=Math.sqrt(y[2]*y[2]+y[3]*y[3])||1,g=9.81,rho=1.225*Math.exp(-y[1]/8500),D=0.5*rho*v*v*p.Cd*p.area;f[0]=y[2];f[1]=y[3];f[2]=p.thrust*y[2]/(v*m)-D*y[2]/(v*m);f[3]=p.thrust*y[3]/(v*m)-D*y[3]/(v*m)-g;f[4]=-p.mdot;}},
{id:6,domain:"Aerospace",icon:"🚀",name:"Hohmann Transfer",stiff:false,
 eq:"\\Delta v=\\sqrt{\\frac{\\mu}{r_1}}\\left(\\sqrt{\\frac{2r_2}{r_1+r_2}}-1\\right)",
 desc:"Minimum energy orbit transfer between two circular orbits.",
 vars:["x","y","vx","vy"],y0:[1,0,0,1],tEnd:12,
 params:{mu:1,r2:2,tBurn:3.14},
 rhs:(t,y,f,p)=>{const r=Math.sqrt(y[0]*y[0]+y[1]*y[1])||1e-10,r3=r*r*r;f[0]=y[2];f[1]=y[3];f[2]=-p.mu*y[0]/r3;f[3]=-p.mu*y[1]/r3;}},
// COSMOLOGY (7-12)
{id:7,domain:"Cosmology",icon:"🌌",name:"Friedmann Expansion",stiff:false,
 eq:"\\left(\\frac{\\dot{a}}{a}\\right)^2=H_0^2\\left(\\frac{\\Omega_m}{a^3}+\\Omega_\\Lambda\\right)",
 desc:"Universe expansion history from the Big Bang to the far future.",
 vars:["a","adot"],y0:[0.001,0.001*Math.sqrt(0.3/0.001**3+0.7)],tEnd:3,
 params:{Om:0.3,OL:0.7,H0:1},
 rhs:(t,y,f,p)=>{const a=Math.max(y[0],1e-20);f[0]=y[1];f[1]=-p.H0*p.H0*(p.Om/(2*a*a*a*a)-p.OL*a)/1;}},
{id:8,domain:"Cosmology",icon:"🌌",name:"Dark Energy (ΛCDM)",stiff:false,
 eq:"H(z)=H_0\\sqrt{\\Omega_m(1+z)^3+\\Omega_\\Lambda}",
 desc:"Hubble parameter evolution with dark energy equation of state w=-1.",
 vars:["a"],y0:[0.01],tEnd:1,
 params:{Om:0.3,OL:0.7,H0:70},
 rhs:(t,y,f,p)=>{const a=Math.max(y[0],1e-20);f[0]=p.H0*a*Math.sqrt(p.Om/(a*a*a)+p.OL);}},
{id:9,domain:"Cosmology",icon:"🌌",name:"Cosmic Inflation",stiff:false,
 eq:"\\ddot{\\phi}+3H\\dot{\\phi}+V'(\\phi)=0",
 desc:"Slow-roll scalar field inflation with quadratic potential V=m²φ²/2.",
 vars:["phi","phidot"],y0:[3,0],tEnd:100,
 params:{m:0.1},
 rhs:(t,y,f,p)=>{const H=Math.sqrt(Math.max(0.5*y[1]*y[1]+0.5*p.m*p.m*y[0]*y[0],1e-30)/3);f[0]=y[1];f[1]=-3*H*y[1]-p.m*p.m*y[0];}},
{id:10,domain:"Cosmology",icon:"🌌",name:"Gravitational Wave Chirp",stiff:false,
 eq:"\\dot{f}=\\frac{96}{5}\\pi^{8/3}\\left(\\frac{G\\mathcal{M}}{c^3}\\right)^{5/3}f^{11/3}",
 desc:"Binary inspiral gravitational wave frequency evolution (LIGO).",
 vars:["freq","phase"],y0:[30,0],tEnd:10,
 params:{Mc:1.2},
 rhs:(t,y,f,p)=>{const k=96/5*Math.pow(Math.PI,8/3)*Math.pow(p.Mc*4.925e-6,5/3);f[0]=k*Math.pow(Math.max(y[0],1),11/3);f[1]=2*Math.PI*y[0];}},
{id:11,domain:"Cosmology",icon:"🌌",name:"Primordial Nucleosynthesis",stiff:true,
 eq:"\\dot{X}_n=-\\lambda_{np}X_n+\\lambda_{pn}(1-X_n)",
 desc:"Neutron-to-proton ratio freeze-out in the early universe.",
 vars:["Xn"],y0:[0.5],tEnd:1000,
 params:{tau:880},
 rhs:(t,y,f,p)=>{const T=10/(1+t*0.01),lnp=1/p.tau*Math.exp(-1.293/T),lpn=1/p.tau*Math.exp(1.293/T);f[0]=-lnp*y[0]+lpn*(1-y[0]);}},
{id:12,domain:"Cosmology",icon:"🌌",name:"Hubble Tension Model",stiff:false,
 eq:"H^2=\\frac{8\\pi G}{3}(\\rho_m+\\rho_r+\\rho_\\Lambda)",
 desc:"Compare early vs late universe H₀ measurements.",
 vars:["a"],y0:[1e-4],tEnd:1,
 params:{Om:0.315,Or:9e-5,OL:0.685,H0:67.4},
 rhs:(t,y,f,p)=>{const a=Math.max(y[0],1e-20);f[0]=p.H0*a*Math.sqrt(p.Om/a**3+p.Or/a**4+p.OL);}},
// INDUSTRY (13-18)
{id:13,domain:"Industry",icon:"🏭",name:"CSTR Reactor",stiff:true,
 eq:"\\dot{C}=\\frac{F}{V}(C_f-C)-kC^n",
 desc:"Continuous stirred-tank reactor with exothermic reaction.",
 vars:["conc","temp"],y0:[1.0,300],tEnd:50,
 params:{F:1,V:10,Cf:2,k0:1e6,Ea:5000,n:2},
 rhs:(t,y,f,p)=>{const k=p.k0*Math.exp(-p.Ea/y[1]);f[0]=p.F/p.V*(p.Cf-y[0])-k*Math.pow(Math.max(y[0],0),p.n);f[1]=p.F/p.V*(300-y[1])+500*k*Math.pow(Math.max(y[0],0),p.n);}},
{id:14,domain:"Industry",icon:"🏭",name:"Heat Exchanger",stiff:false,
 eq:"\\dot{T}_h=-UA(T_h-T_c)/(m_h c_h)",
 desc:"Counter-flow heat exchanger thermal dynamics.",
 vars:["Th","Tc"],y0:[400,300],tEnd:100,
 params:{UA:50,mh:2,mc:3,ch:4200,cc:4200},
 rhs:(t,y,f,p)=>{const Q=p.UA*(y[0]-y[1]);f[0]=-Q/(p.mh*p.ch);f[1]=Q/(p.mc*p.cc);}},
{id:15,domain:"Industry",icon:"🏭",name:"Battery Discharge",stiff:false,
 eq:"\\dot{SOC}=-\\frac{I}{Q_{max}}",
 desc:"Lithium-ion battery State of Charge with Peukert effect.",
 vars:["soc","voltage"],y0:[1.0,4.2],tEnd:3600,
 params:{Qmax:3,R:0.1,I:1},
 rhs:(t,y,f,p)=>{const soc=Math.max(y[0],0.01);f[0]=-p.I/(p.Qmax*3600);f[1]=-p.I*p.R/(soc*soc)-0.001;}},
{id:16,domain:"Industry",icon:"🏭",name:"Population PK Model",stiff:false,
 eq:"\\dot{C}=-\\frac{CL}{V}C+\\frac{dose}{V}\\delta(t)",
 desc:"Pharmacokinetic one-compartment drug elimination model.",
 vars:["conc"],y0:[10],tEnd:24,
 params:{CL:5,V:50},
 rhs:(t,y,f,p)=>{f[0]=-p.CL/p.V*y[0];}},
{id:17,domain:"Industry",icon:"🏭",name:"PID Motor Control",stiff:false,
 eq:"J\\ddot{\\theta}=K_t i-b\\dot{\\theta}",
 desc:"DC motor position control with PID feedback.",
 vars:["theta","omega","integral"],y0:[0,0,0],tEnd:10,
 params:{J:0.01,b:0.1,Kt:0.5,Kp:10,Ki:5,Kd:1,ref:1},
 rhs:(t,y,f,p)=>{const err=p.ref-y[0],u=p.Kp*err+p.Ki*y[2]+p.Kd*(-y[1]);f[0]=y[1];f[1]=(p.Kt*Math.max(-10,Math.min(10,u))-p.b*y[1])/p.J;f[2]=err;}},
{id:18,domain:"Industry",icon:"🏭",name:"Supply Chain Dynamics",stiff:false,
 eq:"\\dot{I}=P-D,\\quad\\dot{P}=k(I^*-I)",
 desc:"Bullwhip effect in production-inventory systems.",
 vars:["inventory","production"],y0:[100,50],tEnd:100,
 params:{Istar:100,k:0.3,D:50},
 rhs:(t,y,f,p)=>{const demand=p.D*(1+0.2*Math.sin(0.2*t));f[0]=Math.max(y[1],0)-demand;f[1]=p.k*(p.Istar-y[0]);}},
// PHYSICS (19-24)
{id:19,domain:"Physics",icon:"⚛️",name:"Lorenz Attractor",chaotic:true,
 eq:"\\dot{x}=\\sigma(y-x),\\;\\dot{y}=x(\\rho-z)-y,\\;\\dot{z}=xy-\\beta z",
 desc:"Deterministic chaos — the butterfly effect. Lorenz (1963).",
 vars:["x","y","z"],y0:[1,1,1],tEnd:40,
 params:{sigma:10,rho:28,beta:2.667},
 rhs:(t,y,f,p)=>{f[0]=p.sigma*(y[1]-y[0]);f[1]=y[0]*(p.rho-y[2])-y[1];f[2]=y[0]*y[1]-p.beta*y[2];}},
{id:20,domain:"Physics",icon:"⚛️",name:"Double Pendulum",chaotic:true,
 eq:"\\text{Lagrangian mechanics, 4 coupled ODEs}",
 desc:"Paradigmatic chaos. Shinbrot et al. (1992).",
 vars:["θ1","ω1","θ2","ω2"],y0:[2.5,0,1.5,0],tEnd:20,
 params:{g:9.81},
 rhs:(t,y,f,p)=>{const d=y[0]-y[2],cd=Math.cos(d),sd=Math.sin(d),den=2-cd*cd;f[0]=y[1];f[1]=(-y[1]*y[1]*sd*cd+p.g*Math.sin(y[2])*cd-y[3]*y[3]*sd-2*p.g*Math.sin(y[0]))/den;f[2]=y[3];f[3]=(y[3]*y[3]*sd*cd+2*(p.g*Math.sin(y[0])*cd+y[1]*y[1]*sd-p.g*Math.sin(y[2])))/den;}},
{id:21,domain:"Physics",icon:"⚛️",name:"Rössler Attractor",chaotic:true,
 eq:"\\dot{x}=-y-z,\\;\\dot{y}=x+ay,\\;\\dot{z}=b+z(x-c)",
 desc:"Simpler chaotic system with folded-band structure. Rössler (1976).",
 vars:["x","y","z"],y0:[1,1,0],tEnd:100,
 params:{a:0.2,b:0.2,c:5.7},
 rhs:(t,y,f,p)=>{f[0]=-y[1]-y[2];f[1]=y[0]+p.a*y[1];f[2]=p.b+y[2]*(y[0]-p.c);}},
{id:22,domain:"Physics",icon:"⚛️",name:"Three-Body Problem",chaotic:true,
 eq:"\\ddot{\\mathbf{r}}_i=-\\sum_{j\\neq i}\\frac{m_j(\\mathbf{r}_i-\\mathbf{r}_j)}{|\\mathbf{r}_i-\\mathbf{r}_j|^3}",
 desc:"Gravitational three-body problem. Chaotic celestial mechanics.",
 vars:["x1","y1","x2","y2","x3","y3","vx1","vy1","vx2","vy2","vx3","vy3"],y0:[-0.5,0,0.5,0,0,0.866,0,0.5,0,-0.5,-0.5,0],tEnd:10,
 params:{},
 rhs:(t,y,f,p)=>{const r12=Math.max(Math.sqrt((y[0]-y[2])**2+(y[1]-y[3])**2),1e-10),r13=Math.max(Math.sqrt((y[0]-y[4])**2+(y[1]-y[5])**2),1e-10),r23=Math.max(Math.sqrt((y[2]-y[4])**2+(y[3]-y[5])**2),1e-10);for(let i=0;i<6;i++)f[i]=y[i+6];f[6]=-(y[0]-y[2])/r12**3-(y[0]-y[4])/r13**3;f[7]=-(y[1]-y[3])/r12**3-(y[1]-y[5])/r13**3;f[8]=-(y[2]-y[0])/r12**3-(y[2]-y[4])/r23**3;f[9]=-(y[3]-y[1])/r12**3-(y[3]-y[5])/r23**3;f[10]=-(y[4]-y[0])/r13**3-(y[4]-y[2])/r23**3;f[11]=-(y[5]-y[1])/r13**3-(y[5]-y[3])/r23**3;}},
{id:23,domain:"Physics",icon:"⚛️",name:"Van der Pol Oscillator",stiff:true,
 eq:"\\ddot{x}-\\mu(1-x^2)\\dot{x}+x=0",
 desc:"Relaxation oscillations — classic stiff ODE benchmark.",
 vars:["x","xdot"],y0:[2,0],tEnd:40,
 params:{mu:3},
 rhs:(t,y,f,p)=>{f[0]=y[1];f[1]=p.mu*(1-y[0]*y[0])*y[1]-y[0];}},
{id:24,domain:"Physics",icon:"⚛️",name:"Damped Driven Pendulum",stiff:false,
 eq:"\\ddot{\\theta}+b\\dot{\\theta}+\\sin\\theta=A\\cos(\\omega t)",
 desc:"Transition from periodic to chaotic motion via driving amplitude.",
 vars:["theta","omega"],y0:[0.1,0],tEnd:100,
 params:{b:0.5,A:1.2,w:0.667},
 rhs:(t,y,f,p)=>{f[0]=y[1];f[1]=-p.b*y[1]-Math.sin(y[0])+p.A*Math.cos(p.w*t);}},
// BIOLOGY (25-30)
{id:25,domain:"Biology",icon:"🧬",name:"Hodgkin-Huxley Neuron",stiff:true,
 eq:"C_m\\dot{V}=I-g_{Na}m^3h(V-E_{Na})-g_Kn^4(V-E_K)-g_L(V-E_L)",
 desc:"Nobel Prize 1963. Action potential in squid giant axon.",
 vars:["V","m","h","n"],y0:[-65,0.053,0.596,0.318],tEnd:50,
 params:{Iext:10},
 rhs:(t,y,f,p)=>{const v=y[0],m=y[1],h=y[2],n=y[3];const am=v+40===0?1:0.1*(v+40)/(1-Math.exp(-0.1*(v+40))),bm=4*Math.exp(-(v+65)/18),ah=0.07*Math.exp(-(v+65)/20),bh=1/(1+Math.exp(-0.1*(v+35))),an=v+55===0?0.1:0.01*(v+55)/(1-Math.exp(-0.1*(v+55))),bn=0.125*Math.exp(-(v+65)/80);f[0]=p.Iext-120*m*m*m*h*(v-50)-36*n*n*n*n*(v+77)-0.3*(v+54.387);f[1]=am*(1-m)-bm*m;f[2]=ah*(1-h)-bh*h;f[3]=an*(1-n)-bn*n;}},
{id:26,domain:"Biology",icon:"🧬",name:"FitzHugh-Nagumo",stiff:false,
 eq:"\\dot{v}=v-v^3/3-w+I,\\;\\tau\\dot{w}=v+a-bw",
 desc:"Simplified neuron excitability model. FitzHugh (1961).",
 vars:["v","w"],y0:[-1,1],tEnd:100,
 params:{a:0.7,b:0.8,tau:12.5,I:0.5},
 rhs:(t,y,f,p)=>{f[0]=y[0]-y[0]**3/3-y[1]+p.I;f[1]=(y[0]+p.a-p.b*y[1])/p.tau;}},
{id:27,domain:"Biology",icon:"🧬",name:"SIR Epidemic",stiff:false,
 eq:"\\dot{S}=-\\beta SI/N,\\;\\dot{I}=\\beta SI/N-\\gamma I",
 desc:"Kermack-McKendrick (1927). Foundational epidemiology.",
 vars:["S","I","R"],y0:[999,1,0],tEnd:200,
 params:{beta:0.3,gamma:0.1,N:1000},
 rhs:(t,y,f,p)=>{const inf=p.beta*y[0]*y[1]/p.N;f[0]=-inf;f[1]=inf-p.gamma*y[1];f[2]=p.gamma*y[1];}},
{id:28,domain:"Biology",icon:"🧬",name:"Lotka-Volterra",stiff:false,
 eq:"\\dot{x}=\\alpha x-\\beta xy,\\;\\dot{y}=\\delta xy-\\gamma y",
 desc:"Predator-prey ecological dynamics. Lotka (1925).",
 vars:["prey","predator"],y0:[10,5],tEnd:30,
 params:{alpha:1.5,beta:1,delta:1,gamma:3},
 rhs:(t,y,f,p)=>{f[0]=p.alpha*y[0]-p.beta*y[0]*y[1];f[1]=p.delta*y[0]*y[1]-p.gamma*y[1];}},
{id:29,domain:"Biology",icon:"🧬",name:"Robertson Kinetics",stiff:true,
 eq:"\\dot{y}_1=-0.04y_1+10^4 y_2 y_3",
 desc:"Extremely stiff chemical kinetics. SUNDIALS flagship benchmark.",
 vars:["y1","y2","y3"],y0:[1,0,0],tEnd:100,
 params:{k1:0.04,k2:3e7,k3:1e4},
 rhs:(t,y,f,p)=>{f[0]=-p.k1*y[0]+p.k3*y[1]*y[2];f[1]=p.k1*y[0]-p.k2*y[1]*y[1]-p.k3*y[1]*y[2];f[2]=p.k2*y[1]*y[1];}},
{id:30,domain:"Biology",icon:"🧬",name:"Gene Toggle Switch",stiff:true,
 eq:"\\dot{u}=\\frac{\\alpha_1}{1+v^\\beta}-u,\\;\\dot{v}=\\frac{\\alpha_2}{1+u^\\gamma}-v",
 desc:"Synthetic biology bistable gene circuit. Gardner et al. (2000).",
 vars:["u","v"],y0:[5,0.1],tEnd:30,
 params:{a1:3,a2:3,beta:2,gamma:2},
 rhs:(t,y,f,p)=>{f[0]=p.a1/(1+Math.pow(Math.max(y[1],0),p.beta))-y[0];f[1]=p.a2/(1+Math.pow(Math.max(y[0],0),p.gamma))-y[1];}}
];
const DOMAINS=["Aerospace","Cosmology","Industry","Physics","Biology"];
